---
- name: ensure directory exists
  file:
    path: "{{ glauth_config_location | dirname }}"
    state: directory
    mode: "0755"

- name: render config
  template:
    src: config.cfg.j2
    dest: "{{ glauth_config_location }}"
    mode: "0644"
